import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components';
import CategoryList from "@/components/CategoryList";
import React from "react";


export const metadata: Metadata = {
  title: 'Anime',
  description: 'Generated by create next app',
};


const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="padding-y px-2 max-width bg-gray-200 min-h-[100vh]">
            <CategoryList/>
            {children}
        </div>
      </body>
    </html>
  );
}
